### ISSUE TITLE
Error in mist_org_alarmtemplate resource nested schema for rules.delivery

### ISSUE THREAD

**Issue by nunopp** [Juniper/terraform-provider-mist#63]
## Describe the bug
rules.delivery attribute seems not working

## To Reproduce
1. Create, update or refresh '.....' resource or datasource
2. Configure the resource/datasource with the following HCL configuration (paste the HCL configuration, remove any sensitive information)
resource "mist_org_alarmtemplate" "alarmtemplate_one" {
  org_id = var.xxx_org
  name   = "Alarm_Template_1"
  delivery = {
    enabled       = true
    to_org_admins = false
    additional_emails = [ omitted emails ]
  }
  rules = {
    dhcp_failure : {
      enabled : true
        delivery : {
          enabled : true
        }
     <omitted other alarms config>
    }
}
4. Use Terraform Apply / Refresh / ... command
5. See error

## Expected behavior
Should enable the alarm delivery via email (alarm notification via email)

## Error Message
When applying changes to mist_org_alarmtemplate.alarmtemplate_one, provider "provider[\"registry.terraform.io/juniper/mist\"]" produced an unexpected new value:
 .rules["dhcp_failure"].delivery.additional_emails: was null, but now cty.ListValEmpty(cty.String).

## Software
 - OS: [ Windows]
 - Terraform Version [ v1.9.7]
 - Provider Version [ v0.2.11]

**Comment by nunopp** [comment]
Hi Thomas, when this can be added to a new realease?
Thank you

**Comment by tmunzer** [comment]
Hi @nunopp ,
Sorry, there is some changes I would like to include into the next version. I'll make sure to release a new version end of this week with the fix for this issue.

Best regards

**Comment by tmunzer** [comment]
Hi @nunopp, 

Version v0.2.12 has been published with the fix.

Best regards

**Comment by nunopp** [comment]
Hi @tmunzer , after the upgrade when doing the apply I've got errors (mainly for attributes = null) on the resource mist_org_wlan, some examples:
...produced an unexpected new value: .dns_server_rewrite.radius_groups: was cty.MapValEmpty(cty.String), but now null
...produced an unexpected new value: .ap_ids: was null, but now cty.ListValEmpty(cty.String).
...produced an unexpected new value: .app_limit.apps: was cty.MapValEmpty(cty.Number), but now null.
any thoughts?

**Comment by tmunzer** [comment]
Yes, this should occur only during the first config sync because some default values have been updated.
Let me know if you are seeing it afterward.

**Comment by tmunzer** [comment]
For information, I added a [release note](https://registry.terraform.io/providers/Juniper/mist/latest/docs/guides/release_note_0.2.12) page in the Provider documentation.
It is listing all the default value changes that have been added to this release (none will impact the configuration deployed on the APs)

**Comment by nunopp** [comment]
![image](https://github.com/user-attachments/assets/d4c2206c-c6cb-43df-96e1-d885ff698132)
it is still stating these changes but I'm unable to apply cause it gives error results ("Error: Provider produced inconsistent result after apply") examples of the ones provided above. What do you suggest to do?

**Comment by tmunzer** [comment]
Sorry for the late reply @nunopp, I'll work on it

**Comment by tmunzer** [comment]
Hi @nunopp,

I just released v0.2.13. Can you test it?

Thanks

**Comment by nunopp** [comment]
Hi @tmunzer , plugin crashed
![image](https://github.com/user-attachments/assets/ea9bc8df-df3c-4685-b59d-eb9267ecad65)

Thanks

**Comment by tmunzer** [comment]
Sorry for that, I just released v0.2.14 which should fix this issue

**Comment by tmunzer** [comment]
Hi @nunopp , no problem.
I just fixed the issue (there was a change in the Go SDK and I missed some places where to update the code).
The new version should be better.

Can you check?
Thanks.

**Comment by nunopp** [comment]
@tmunzer however I've noticed that it works with vs 0.2.14, only when moving to 0.2.15 the above errors are triggered

**Comment by tmunzer** [comment]
yes, I updated the Go SDK in-between (mostly because of fixes in the OpenAPI Spec used to generate the SDK, but it also bring some other changes in the SDK), which introduced this change. 
I updated the required code in 0.2.15, but it seems I missed this part.

**Comment by nunopp** [comment]
@tmunzer with version 0.2.16 I'm still getting the errors for mist_org_psk for vlan_id, however seems fixed for mist_org_wlan> dynamic_vlan.default_vlan_ids

**Comment by tmunzer** [comment]
sorry for that. I just released a new version fixing this issue.

**Comment by nunopp** [comment]
@tmunzer the new version 0.2.17 apparently fixed all the errors, thank you!
Also I confirm the initial issue is also working (Error in mist_org_alarmtemplate resource nested schema for rules.delivery)
Thanks a lot for this!
Regards

**Comment by tmunzer** [comment]
Thanks for the confirmation. I'm closing this issue.
